### ISSUE TITLE
Array comparison : missing index '0'

### ISSUE THREAD

**Issue by ecappa** [lukascivil/TreeWalker#12]
Hi, 
When I compare 2 array (no key, just array for the root element), structPathArray miss the first 'key'.
I had to add to change your test :
$path = $currentpath !== '' ? $currentpath . "/" . $key : sprintf($key);

Do you prefer a pull request ?

**Comment by ecappa** [comment]
Made my own branch : https://github.com/ecappa/TreeWalker/tree/ecappa-patch-1

**Comment by lukascivil** [comment]
Okay, thank you for your colaboration. I did some testing with your  observation and everything worked perfectly for your problem and for other cases. Please make the pull request.

**Comment by ecappa** [comment]
Done! 
Thanks!
