### ISSUE TITLE
Next tag date?

### ISSUE THREAD

**Issue by mattermack** [lukascivil/TreeWalker#14]
Lukas,

When is the next tag coming?  This would help lower the stability level in Packagist

**Comment by mattermack** [comment]
@lukascivil , any thoughts on timing?

**Comment by lukascivil** [comment]
Hi mattermack, i did not understand so well. I'm not an expert with packagist. Could you explain your need?
Thank you for your comment and for always collaborating.

**Comment by mattermack** [comment]
Thanks @lukascivil.   Packagist / composer requires you to set a few flags to pulling in the head of master.   "prefer-stable": true, "minimum-stability": "dev".   Folks tend not to like to set their minimum-stability to dev as that can result in unstable code in their production projects.   Thus, since head of TreeWalker is pretty stable, can you add a tag, let's say 0.42 or 0.10 if that was the convention you were going with (based on other tags)
