### ISSUE TITLE
Check only keys, not values

### ISSUE THREAD

**Issue by stefkes** [lukascivil/TreeWalker#15]
Hey thanks for this nice lib.

Is there any way of just checking the keys / labels and ignoring the values?

**Comment by lukascivil** [comment]
Hi. Why a do not compare keys ? First, i saw arrays as ordered list and object as unordered list.
For example:
if i have
 `{
    "glossary": "",
    "glossary2": ""
}` 
and 
`{
    "glossary2": "",
    "glossary": ""
}`

output: the two structures are semantically identical.

but, if i have 

 `[
    "glossary": "",
    "glossary2": ""
]` 
and 
`[
    "glossary2": "",
    "glossary": ""
]`

the algorithm compare looking the keys [0,1].

However, could you send me a simple example with input and output that you imagine for the diff method? (just to illustrate your idea).
