### ISSUE TITLE
Add PSR standards

### ISSUE THREAD

**Issue by sergey-shevchenko** [lukascivil/TreeWalker#2]
It would be cool to bring the code into accordance with [PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md) and [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)

As well as it would be great to have proper [phpDocs](https://www.phpdoc.org/docs/latest/index.html)

**Comment by sergey-shevchenko** [comment]
partially covered by pull request #3

**Comment by lukascivil** [comment]
I had no time to make these repairs. Thank you my friend.
