### ISSUE TITLE
nested array 

### ISSUE THREAD

**Issue by gfirem** [lukascivil/TreeWalker#7]
Hi, i face an issue. I had two array and need a nested array instead of parent/child, it will be more usefully in my case parent => [child => [] ]. 

My full example, first the arrays to compare, the original result and the desire result. 

		$array1 = array(
			0 => array(
				"key" => "val",
				"etc" => "val",
			),
		);
		$array2 = array(
			0 => array(
				"key" => "val1",
				"etc" => "val2",
			),
		);
*****************************************************************************************
		$array1 = array(
			"edited" =>
				array(
					"0/key" => array( "oldvalue" => "val", "newvalue" => "val1" ),
					"0/etc" => array( "oldvalue" => "val", "newvalue" => "val2" )
				)
		);

*****************************************************************************************
		$array1 = array(
			"edited" =>
				array(
					"0" => array(
						"key" => array( "oldvalue" => "val", "newvalue" => "val1" ),
						"etc" => array( "oldvalue" => "val", "newvalue" => "val1" )
					),
				)
		);

Thanks in advance for your help

**Comment by lukascivil** [comment]
- When you use getdiff($array2, $array1, **default = false**) -> with slashs

```php
array(
	"0/key" => array( "oldvalue" => "val", "newvalue" => "val1" ),
	"0/etc" => array( "oldvalue" => "val", "newvalue" => "val2" )
)
```
-  With true param, getdiff($array2, $array1, **true**) -> nested element

```php
array(
	"0" => array(
		"key" => array( "oldvalue" => "val", "newvalue" => "val1" ),
		"etc" => array( "oldvalue" => "val", "newvalue" => "val1" )
	)
)
```

I hope that I have helped ; )

**Comment by gfirem** [comment]
Thanks, i will test and back with the result

**Comment by gfirem** [comment]
Thanks i was using a old version.
